### ISSUE TITLE
How to resolve the warning when I using your plugin?

### ISSUE THREAD

**Issue by B1anker** [Katochimoto/rollup-plugin-less2#1]
`(node:29359) DeprecationWarning: Calling an asynchronous function without callback is deprecated.`
Is there any asynchronous function in your code?

**Comment by Katochimoto** [comment]
Hi. Thank you!
I used asynchronous `fs.writeFile` with `await`. This has led to the warning.
It's fixed in release 3.0.1.

**Comment by B1anker** [comment]
Hey, did you publish it in npm?

**Comment by Katochimoto** [comment]
Yes, immediately after the fix.
```
# yarn info rollup-plugin-less2
{ name: 'rollup-plugin-less2',
  description: 'A rollup plugin for less files, support css modules',
  'dist-tags': { latest: '3.0.1' },
```

**Comment by B1anker** [comment]
got it
